In [2]:
import os
import sys

import json
import random
import time
import pandas as pd
import seaborn as sns

from datetime import datetime
from dotenv import load_dotenv
from pathlib import Path

In [3]:
MODULES_PATH = Path("../modules").resolve()

if str(MODULES_PATH) not in sys.path:
    sys.path.insert(0, str(MODULES_PATH))

import corpus
import api

from dev import rel, print_epi_summary
from data_config import DATA_CONFIG, FEW_SHOT_PATH
from few_shot import get_few_shot_examples
from error_sampling import error_summary, sample_errors
from plotting import plot_dist_comparison

import pipeline

# Config.

### Development Config.

In [4]:
load_dotenv()

# ---------- Set seed to 42 ----------
SEED = int(os.getenv("SEED", 42))
random.seed(SEED)

# ---------- Print confirmation ----------
print(
    f"Set random seed to {SEED} at "
    f"{datetime.now().strftime('%Y-%m-%d %H:%M')}"
)

Set random seed to 42 at 2026-08-23 11:39

### EPI Config.

In [24]:
# ---------- Manual EPI config. entry ----------
EPI_NUM = "002"
DATASET_SPLIT = "train"

# ---------- Config. whether EPI config's API should be called again ----------
CALL_API = True

# ---------- Config. whether error distribution figure should be saved ----------
SAVE_FIG = True

# Corpus Loading

### Load Abstracts

In [25]:
# ---------- Get abstracts path ----------
ABSTRACTS_PATH = DATA_CONFIG[DATASET_SPLIT]["paths"]["abstracts"]
SAMPLE_SIZE = DATA_CONFIG[DATASET_SPLIT]["sample_size"]

# ---------- Load corpus from path ----------
abstracts_corpus = corpus.load_corpus(ABSTRACTS_PATH, sample_size=SAMPLE_SIZE)
print(f"Abstracts dataset length: {len(abstracts_corpus)}")

Abstracts dataset length: 400

### Get Ground Truths

In [26]:
# ---------- Manually Set Ground Truth Paths ----------
GT_PATH = DATA_CONFIG[DATASET_SPLIT]["paths"]["ground_truths"]
ENTITIES_GT_PATH = DATA_CONFIG[DATASET_SPLIT]["paths"]["entities_ground_truths"]

# ---------- Fetch BioRED Ground Truths ----------
abstracts_ground_truths = corpus.get_corpus_gt_csv(abstracts_corpus, GT_PATH)
entities_ground_truths = corpus.get_corpus_gt_csv(abstracts_corpus, ENTITIES_GT_PATH)

In [27]:
entities_ground_truths.head()

,pmid,entity_id,text,entity_type,identifier,start,end,split
0,10491763,0,Hepatocyte nuclear factor-6,GeneOrGeneProduct,3175,0,27,train
1,10491763,1,type II diabetes,DiseaseOrPhenotypicFeature,D003924,74,90,train
2,10491763,2,insulin,GeneOrGeneProduct,3630,140,147,train
3,10491763,3,hepatocyte nuclear factor (HNF)-6,GeneOrGeneProduct,3175,184,217,train
4,10491763,4,maturity-onset diabetes,DiseaseOrPhenotypicFeature,D003924,292,315,train

In [28]:
abstracts_ground_truths.head()

,pmid,entity_1,entity_1_type,entity_1_identifier,relation,entity_2,entity_2_type,entity_2_identifier,split
0,10491763,Hepatocyte nuclear factor-6,GeneOrGeneProduct,3175,Association,type II diabetes,DiseaseOrPhenotypicFeature,D003924,train
1,10491763,glucose,ChemicalEntity,D005947,Positive_Correlation,insulin,GeneOrGeneProduct,3630,train
2,10491763,glucose,ChemicalEntity,D005947,Association,type II diabetes,DiseaseOrPhenotypicFeature,D003924,train
3,10661407,Langerin,GeneOrGeneProduct,50489,Bind,mannose,ChemicalEntity,D008358,train
4,10788334,breast or ovarian cancer,DiseaseOrPhenotypicFeature,D001943,Positive_Correlation,5382insC,SequenceVariant,c|INS|5382|C,train

In [29]:
entities_ground_truths["entity_type"].unique()

<StringArray>
[         'GeneOrGeneProduct', 'DiseaseOrPhenotypicFeature',
             'ChemicalEntity',              'OrganismTaxon',
            'SequenceVariant',                   'CellLine']
Length: 6, dtype: str

In [30]:
os.getcwd()

'e:\\Users\\wesle\\biomedical_kg_thesis\\src\\experiments'

In [31]:
# ---------- Turn ground truth DataFrame into structured dict ----------
ground_truths = corpus.get_gt_dict(abstracts_ground_truths, entities_ground_truths)

### Few-Shot Construction

In [32]:
# ---------- If FS block does not exist, create FS block, else pass ----------
if not os.path.exists(FEW_SHOT_PATH):

    few_shot_block = get_few_shot_examples(
        path_to_train_set=DATA_CONFIG["train"]["paths"]["abstracts"],
        path_to_train_gts=DATA_CONFIG["train"]["paths"]["ground_truths"],
        biored_train_samples=abstracts_corpus,
        few_shot_export_path=FEW_SHOT_PATH
    )
    print(f"Generated and exported new few-shot block to '{FEW_SHOT_PATH}'")
else:
    with open(FEW_SHOT_PATH) as f:
        few_shot_block = f.read()
    print(f"Imported existing few-shot block from '{FEW_SHOT_PATH}' at {datetime.now().strftime('%Y-%m-%d %H:%M')}.")

Imported existing few-shot block from '../../data/few_shot/few_shot_block.txt' at 2026-08-23 13:12.

### Import BioRED Extraction Guidelines

In [33]:
# ---------- Import BioRED guidelines text file for prompt refinement ----------
with open("../../data/processed/biored/guidelines.txt", "r", encoding="utf-8") as f:
    biored_ext_guidelines = f.read()

# ---------- Print preview ----------
print(f"{biored_ext_guidelines[:500]}...")

## Guideline of the entities

### General rules
- Annotate all the spans of all the six concept types.
- The full text can be accessed to clarify the concept spans and identifiers.
- The abbreviation and its long form should be annotated separately if possible. prostaglandin E2 (PGE2) in the text, “prostaglandin E2” and “PGE2” should be both annotated to chemicals with the same identifier (D015232).
- Annotate both the full name and abbreviation in one entity, if the boundary of the entity cover...

# OpenAI Luna API Call

### EPI Setup

In [34]:
# ---------- Create EPI setup dictionary ----------
# - Keys: "dataset", "id", "eval_version", "notes", "reuse_api_call", "prompt"
epi_setup = pipeline.setup_epi(EPI_NUM, DATASET_SPLIT)

# ---------- Print summary ----------
print_epi_summary(
    epi_num=EPI_NUM,
    prompt_version=epi_setup["prompt"]["version"],
    eval_version=epi_setup["eval_version"],
    notes=epi_setup["notes"],
    reuse_api_call=epi_setup["reuse_api_call"]
)

Cell ran at 2026-08-23 13:12 for epi_002
 - Prompt version: v2
 - Evaluation version: v2
 - Notes: Implemented BioRED extraction guidelines and entity and relation type rules & added relaxed matching.
 - Reuse API Call: False

### API Call

In [ ]:
# ---------- API call / import existing EPI API log ----------
if CALL_API:
    # ---------- Create client ----------
    client = api.create_client(timeout=120, max_retries=2)

    # ---------- If prompt version is different from previous EPI, call API, else pass ----------
    if not epi_setup["reuse_api_call"]:

        print(f"Running API call for {epi_setup["id"]} ({epi_setup["dataset"]})...")

        # Fetch raw prompt template
        prompt_template = epi_setup["prompt"]["template"]

        # Begin timer
        start_time = time.perf_counter()

        # Initiate outputs list
        outputs = []

        current_abstract_num = 1

        # Begin looping through abstract dataset rows - one call per row
        for index, row in abstracts_corpus.iterrows():
            abstract = row["abstract"]

            num_abstracts = abstracts_corpus.shape[0]

            # Replace prompt template's placeholders with abstract, few_shot & guidelines
            prompt = (
                prompt_template
                .replace("{abstract}", abstract)
                .replace("{few_shot_block}", few_shot_block)
                .replace("{biored_ext_guidelines}", biored_ext_guidelines)
            )

            # Store row's response
            response = client.responses.create(
                model="gpt-5.6-luna",
                input=prompt
            )

            # Append response to outputs list
            outputs.append({
                "pmid": row["pmid"],
                "output": response.output_text
            })

            progress_time = time.perf_counter() - start_time
            avg_time_per_abstract = progress_time / current_abstract_num
            est_time_remaining = avg_time_per_abstract * (num_abstracts - current_abstract_num)
            minutes = int(est_time_remaining // 60)
            seconds = est_time_remaining % 60

            print(
                f"\rCompleteled extraction for abstract {current_abstract_num} of {num_abstracts} "
                f"({current_abstract_num / num_abstracts * 100:.1f}%; "
                f"Est. time remaining: {minutes}m {seconds:.0f}s).",
                end="",
                flush=True
            )
            current_abstract_num += 1

        # End time, store elapsed time & print result
        elapsed_seconds = time.perf_counter() - start_time
        print(f"\n\nAPI calls took {elapsed_seconds:.1f}s ({elapsed_seconds/60:.1f} min) for {len(outputs)} abstracts\n")

        print(f"Successfully ran API call at {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        print(f" - Prompt verion: {epi_setup["prompt"]["version"]}")
        print(f" - Evalaution verion: {epi_setup["eval_version"]}")
        print(f" - Run notes: {epi_setup["notes"]}")
        print(f" - Elapsed time: {elapsed_seconds:.1f}s ({elapsed_seconds/60:.1f}")
    else:
        prev_epi_id = f"epi_{int(EPI_NUM) - 1:03d}"

        with open(f"{DATA_CONFIG[DATASET_SPLIT]["paths"]["epi_dir"]}/{prev_epi_id}.json") as f:
            prev_epi_log = json.load(f)

        outputs = prev_epi_log["outputs"]
        prompt_template = prev_epi_log["prompt"]
        elapsed_seconds = prev_epi_log["time_taken"]

        print(f"Reused API call from {prev_epi_id}.")

    output_info = {
        "epi_id": epi_setup["id"],
        "outputs": outputs,
        "time_taken": elapsed_seconds,
        "raw_prompt": prompt_template,
        "epi_notes": epi_setup["notes"],
        "prompt_version": epi_setup["prompt"]["version"],
        "eval_version": epi_setup["eval_version"],
        "export_path": DATA_CONFIG[DATASET_SPLIT]["paths"]["epi_dir"]
    }
else:
    print(f"Pipeline run not executed at {datetime.now().strftime('%Y-%m-%d %H:%M')} (PIPELINE_RUN = False).")

Created client:
 - Timeout: 120
 - Max retries: 2

Running API call for epi_002 (biored_train)...
Completeled extraction for abstract 5 of 400 (1.2%; Est. time remaining: 121m 58s).

In [ ]:
# ---------- Parse outputs, evaluate extractions, export EPI results ----------
if CALL_API:
    epi_log = pipeline.process_epi(output_info, ground_truths, dataset=epi_setup["dataset"])
else:
    print(f"Pipeline run not executed at {datetime.now().strftime('%Y-%m-%d %H:%M')} ('CALL_API = False').")

Parsed 400 extractions, 1 failed to parse as JSON
Saved epi_001 to ../../data/results/epis/biored_train

# Error Analysis

### Summary Table

In [ ]:
# ---------- If EPI API call does not exist in kernel state, import existing EPI log ----------
if not CALL_API:
    try:
        with open(f"../../data/results/epis/{epi_setup["dataset"]}/{epi_setup["id"]}.json") as f:
            epi_log = json.load(f)
    except:
        raise ValueError(
            f"EPI log cannot be imported: "
            f"'../../data/results/epis/{epi_setup["dataset"]}/{epi_setup["id"]}.json' does not exist."
        )

error_summary(epi_log)

`epi_001` Error Summary:

Metric    Precision  Recall   F1
Entity          0.0     0.0  0.0
Relation        0.0     0.0  0.0

### Distribution Comparison

In [ ]:
if EPI_NUM == "001":
    print(
        "Extraction distribution analaysis is not conducted on 'epi_001' - "
        "extractions are not bound to fixed sets."
    )
elif epi_setup["reuse_api_call"] == True:
    print(
        f"EPI uses previous EPI's prompt - "
        f"did not plot ground truth/extraction distribution figure for `epi_{EPI_NUM}`."
    )
else:
    plot_dist_comparison(epi_log, ground_truths, save=SAVE_FIG)

Extraction distribution analaysis is not conducted on 'epi_001' - extractions are not bound to fixed sets.

## Relations

### False Positives

In [ ]:
if DATASET_SPLIT == "train":
    # ---------- False positives ----------
    relation_fp = epi_log["errors"]["errors"]["relations"]["false_positives"]

    print(f"Count: {len(relation_fp)}")

    display(sample_errors(relation_fp, sample_size=200))

Count: 11047
Sample size: 200

[[21070631, 'inflammation', 'occurs in', 'brain'],
 [16412238, 'y355x', 'has_zygosity', 'heterozygous mutation'],
 [29045486,
  'pro-apoptotic/inflammatory signaling',
  'contributes_to',
  'apoptotic cell death'],
 [19923525,
  'nimodipine (nimo)',
  'does not improve in absence of hypotension',
  'latency time'],
 [17615423,
  'rhabdomyolysis',
  'associated_with_elevated',
  'alanine aminotransferase'],
 [17083016, 'sp-a1', 'encodes', 'surfactant protein a (sp-a)'],
 [18310445, 'bmp-4', 'favours', 'fsh rather than lh synthesis and secretion'],
 [20801104,
  '-616c/g',
  'located_in_promoter_region_of',
  'dopamine d4 receptor (drd4) gene'],
 [20477932,
  'cocaine administration',
  'decreases',
  'glutathione peroxidase activity'],
 [24535067, 'fentanyl', 'prevents', 'etomidate-induced myoclonus'],
 [18366737, 'fh variants', 'includes', '93 pathogenic variants'],
 [15748645, 'ultraviolet (uv) b', 'increases_risk_of', 'skin cancer'],
 [26102294, 'failure of autophagy', 'causes accumulation of', 'p16ink4a'],
 [27172902,
  'il-10',
  'is required for induction of',
  'tolerogenic dendritic cells'],
 [24477591,
  '-930g allele',
  'risk factor for',
  'coronary artery disease (cad)'],
 [20080983, 'modafinil', 'shortens', 'rem sleep latency'],
 [21699520, 'g.2885g>c', 'occurs_in', 'sporadic bccs'],
 [18366737, 'fumarate hydratase', 'also known as', 'fumarase'],
 [16418600, 'p.f366l', 'has zygosity', 'heterozygous'],
 [20105310, 'subcutaneous (sc) adipose tissue', 'analyzed_by', 'microarray'],
 [15266215,
  'valdecoxib',
  'assessed for incidence of',
  'cardiovascular thrombotic events'],
 [15278670, 'sevoflurane', 'reduces', 'lidocaine-induced convulsions'],
 [15033202, 'preventive care', 'improves', 'prognosis'],
 [28368537, 'msx1', 'regulates', 'uterine receptivity'],
 [19445921, 'isoproterenol', 'decreases', 'catalase'],
 [28398555, 't71n', 'causes', 'perturbed calcium signalling'],
 [24100257, 'zolmitriptan', 'used_for', 'migraines'],
 [17244258,
  'postjunctional beta-adrenoceptor-mediated relaxations',
  'are_reduced_in',
  'cyclophosphamide-induced cystitis'],
 [18397285,
  'dominant-negative mechanism',
  'causes',
  'type 2a von willebrand disease (vwd)'],
 [16418600, '457_458insg', 'was not detected in', '126 sids cases'],
 [20080916, 'promoter insertion/deletion (indel)', 'genotyped_in', 'controls'],
 [20335448,
  'tj',
  'has_diagnosis',
  'generalized glucocorticoid resistance syndrome'],
 [21163864, 'pcr', 'amplifies', 'region of interest in the agt gene'],
 [1711760,
  'ischemic core',
  'has no hypertension-associated difference in',
  'sg'],
 [24853300,
  'amyloid precursor protein/presenilin transgenic mice',
  'are aggravated by removal of',
  'cb'],
 [10788334, 'related females', 'are affected by', 'ovarian cancer'],
 [20105310, 'omental (om) adipose tissue', 'analyzed_by', 'microarray'],
 [25986755, 'prenatal caffeine exposure (pce)', 'increases', 'urine protein'],
 [20801104,
  'allele-specific polymerase chain reaction analysis',
  'used_to_genotype',
  '-616c/g'],
 [20105280,
  'ras activation',
  'fails to sustain proliferation in',
  'lens epithelial cells'],
 [20708777,
  'cyp11b2',
  'confers_susceptibility_to',
  'postoperative hypertension'],
 [27999109, 'type i ifn a/b receptor', 'also_known_as', 'ifnar'],
 [18779591, 'multiple fibroadenomas (mfa)', 'is_a', 'breast diseases'],
 [19101703, 'normal allele', 'contains', '(gcg)6(gca)3gcg'],
 [17628794, 'urolithiasis', 'is characterized by', 'stone formation'],
 [19508969, 'nphp11', 'lacks', 'neurological signs'],
 [18791947,
  'propositus',
  'has_variant',
  'homozygous four bases deletion (tgag)'],
 [24743235, 'csf-1', 'dampens', 'mast cell generation'],
 [18182964,
  'clonidine',
  'studied_in',
  'attention-deficit/hyperactivity disorder (adhd)'],
 [15200408, 'major uroplakin mutations', 'may_cause', 'postnatal lethality'],
 [21195121, 'l-name', 'decreases', 'convulsion incidence'],
 [21699520,
  'polymerase chain reaction',
  'amplified',
  'five exons of ptch1 and ptch2'],
 [18439317,
  'magnetic resonance imaging (mri)',
  'interpreted_using',
  "schneiderman's classification"],
 [24768818, 'dfg-out conformation', 'stabilized_by', 'salt bridge'],
 [20588063, 'nephrin', 'further decreased by', 'day 4'],
 [15241482,
  '192rr homozygotes',
  'replicated in',
  '541 danish individuals from the oldest cohort'],
 [28428256, 'lipopolysaccharide (lps)', 'causes', 'barrier dysfunction'],
 [15970799, 'slco1b1*15', 'decreases transporting activity of', 'oatp1b1'],
 [17327131, 'pneumotoxicants', 'have_potential', 'carcinogenic effects'],
 [22303482, 'tbx21 promoter snp rs17250932', 'variant_of', 'tbx21'],
 [20520283,
  'asenapine at 5 mg twice daily (bid)',
  'associated_with_lower',
  'extrapyramidal symptoms'],
 [27779699, 'flnb', 'encodes', 'filamin b'],
 [18752389, 'liver transplantation', 'treated', 'fulminant hepatic failure'],
 [16584858, 'myocardial infarction', 'alters', 'glutathione reductase'],
 [17572393,
  'immunohistochemistry',
  'used_to_evaluate',
  'offspring rat cerebellum'],
 [15749661, 'c282y mutation', 'associated with', 'hemochromatosis'],
 [19110214,
  'conformational binding loops',
  'mediates_interactions_with',
  'tenascins'],
 [11773892,
  '1-year serum creatinine',
  'associated odds ratio',
  'odds ratio 2.6'],
 [27640183, 'a82', 'binds', 'epo receptor (epo-r)'],
 [9294109,
  'dmpk-/- myotubes',
  'increase',
  'resting intracellular ca2+ concentration'],
 [18310445, 'bmp-4', 'enhances', 'activin+gnrh-induced fshbeta mrna'],
 [23952588, 'multiethnic malaysian patients', 'includes', 'malays'],
 [24768818, 'ddr2', 'associated_with', 'mutation'],
 [20523265, 'cata', 'protective against', 'wet amd'],
 [22048266, 'trisomy of the 21st chromosome', 'causes', 'down syndrome (ds)'],
 [25305591,
  'pituitary adenylyl cyclase-activating polypeptide (pacap)',
  'signals_through',
  'pac1'],
 [17033686, 'lenz microphthalmia syndrome', 'has_phenotype', 'microphthalmia'],
 [15278670, 'enflurane', 'reduces rise in', 'blood pressure'],
 [26102294,
  'exhaustion of autophagy',
  'causes',
  'terminal cellular senescence'],
 [12442272, 'homozygotes', 'share', 'rare haplotype'],
 [26115410,
  'early-life ias exposure',
  'may_induce',
  'epigenetic reprogramming'],
 [18987260, 'losartan', 'slows_progression_to', 'end-stage renal disease'],
 [11773892,
  'orthotopic liver transplantation',
  'associated with',
  'chronic renal failure'],
 [20579626,
  'recessive osteogenesis imperfecta',
  'associated with',
  'delayed tooth eruption'],
 [24132704, 'diazinon', 'increases', 'triglyceride'],
 [19779499,
  'skeletal muscle calcium channel alpha-subunit',
  'has',
  'four transmembrane domains (i-iv)'],
 [19672862, 'pkcalpha', 'studied_in', 'ishikawa cells'],
 [15145918, 'alpha-methyldopa', 'induces', 'hypotension'],
 [21771880,
  'single nucleotide polymorphisms (snps)',
  'located_in',
  'promoter'],
 [17595233, 'card15 variants', 'increases', 'gasca titers'],
 [15188772, 'medical errors', 'causes', 'acute iatrogenic overdose'],
 [19631624, 'allocortical regions', 'vulnerable_to', 'neurotoxic effects'],
 [16410744,
  'primary (de novo) glioblastomas',
  'studied_in',
  'japanese patients'],
 [15122708,
  'early-onset, recessive form with mallory body-like inclusions (mb-drms)',
  'shares_clinical_features_with',
  'sepn-related myopathy (sepn-rm)'],
 [16843501,
  'alkaline single cell gel electrophoresis',
  'evaluates',
  'dna damage'],
 [17177139, 'e333d', 'substitutes', 'glutamic acid 333'],
 [16369751,
  'cardiotoxicity',
  'leads to discontinuation of',
  '5-fluorouracil (5-fu)'],
 [18657397,
  'penicillin-g potassium',
  'injected_into',
  'left lateral ventricle'],
 [1711760, 'middle cerebral artery occlusion', 'abbreviation', 'mcao'],
 [19631624, 'cannabis', 'may_confound', 'ecstasy-related deficits'],
 [22808010, 'epo', 'upregulates', 'tnfr-sf13c'],
 [28368537, 'uterine receptivity', 'rather_than', 'embryo competency'],
 [20828385, 'temsirolimus', 'inhibits', 'mtor'],
 [18593936, 'nf-kappab', 'regulates', 'survivin'],
 [28368537,
  'lifr flx/d:ltf cre/+ females',
  'contain',
  'unimplanted blastocysts'],
 [20534142, 'rs6232', 'decreases', 'homair'],
 [17965424, 'etoricoxib', 'associated with', 'renovascular adverse events'],
 [11773892, 'chronic renal failure', 'abbreviation', 'crf'],
 [15200408, 'healthy individuals', 'serves_as', 'control population'],
 [18768591,
  'gene-targeted mice lacking sgk1 (sgk1(-/-))',
  'exhibits',
  'blunted volume retention'],
 [21666969, 'lifestyle modification', 'causes', 'weight loss'],
 [26516699, 'pdx1-cre', 'component_of', 'krasg12d;pdx1-cre (kc) mouse model'],
 [15970799, 'slco1b1*15+c1007g', 'does not alter Km of', 'atorvastatin'],
 [19082493, 'high-risk group', 'treated_with', '5fu chemotherapy'],
 [20105280, 'prox1', 'is critical for', 'cell cycle exit'],
 [26027517, 'lpa', 'accelerates_resolution_of', 'gamma-h2ax'],
 [17975693, 'ciprofloxacin', 'evaluated_by', 'elevated zero maze'],
 [28260056, 'hypoxia', 'regulates', 'igf system'],
 [18681856, 'genomic dna', 'extracted_from', 'peripheral blood leukocytes'],
 [17244258,
  'atropine',
  'reduces_at_low_frequency_in',
  'inflamed preparations'],
 [20415560, 'pharmacogenomic strategy', 'screens', 'diabetes mellitus (dm)'],
 [27860244, 'epz015666', 'inhibits phosphorylation of', 'ikba'],
 [26731607, 'gadd45a', 'arrests', 'cell cycle progression'],
 [19370764, 'c.611delg', 'located_in', 'coding region'],
 [9647766, 'ndufs6 pseudogene', 'associated with', 'human chromosome 6'],
 [17286451, 'retinoblastoma (rb)', 'affects', 'rb patients'],
 [18410508, 'striatal microglia', 'constitutively_expresses', 'egfp'],
 [24902786, 'letrozole', 'inhibits', 'aromatase'],
 [27084744, 'dapt', 'induces', 'p27kip1'],
 [16920333, 'adverse effects', 'assessed in', 'eeg patterns'],
 [16160878, 'urotensin-ii (u-ii)', 'stimulates', 'thyrotropin secretion'],
 [15897593, 'doxorubicin', 'has', 'hematologic activity'],
 [16904497, '50-year-old woman', 'has', 'right leg pain'],
 [18166824, 'msh5', 'involved_in', 'meiotic recombination'],
 [17877751,
  'normal control samples',
  'include',
  'northern european populations'],
 [21325775,
  'apoe osaka',
  'associated_with',
  'lipoprotein glomerulopathy (lpg)'],
 [18439317, 'g allele', 'reference_allele_for', 'd allele'],
 [18772193, 'epsinr', 'exists_in', 'humans'],
 [27172902, 'cisplatin', 'downregulates', 'mhc class ii'],
 [15630069, 'clozapine-treated group', 'treated with', 'clozapine'],
 [19365571, 'p.q298x', 'affects codon', 'glutamine'],
 [25946186, 'tipe2', 'potential_marker_for', 'lung cancer diagnosis'],
 [18356633,
  'prospective, randomized, open-label trial',
  'conducted_in',
  'university-affiliated medical center'],
 [20523265,
  'cfb',
  'associated with',
  'age-related macular degeneration (amd)'],
 [16506214, 'five snps', 'genotyped in', '782 controls'],
 [24055495,
  "dementia of sporadic alzheimer's disease (sad) type",
  'associated_with',
  'insulin-receptor (ir) system dysfunction'],
 [16157158,
  'cys/ser',
  'associated_with_intermediate',
  'body mass index (bmi)'],
 [28512644, 'ccl5', 'variation associated with', 'sod2 t2734c'],
 [21911891,
  'morbid obesity',
  'associated_with',
  'non-alcoholic fatty liver disease (nafld)'],
 [15630069,
  'clozapine-treated group',
  'has higher',
  'fasting serum insulin concentrations'],
 [28368537, 'cre recombinase', 'is_restricted_to', 'endometrial glands (ges)'],
 [20583543,
  'dna sequencing',
  'performed on aberrant PCR-SSCP amplicons',
  'srd5a2 gene'],
 [17000021,
  'r620w',
  'associated_with_risk_of',
  'multiple autoimmune diseases'],
 [21238926, 'nanos (nos)', 'is_downregulated_in', 'daughter cell'],
 [21911891, 'obese patients', 'had_higher', 'triglycerides'],
 [16755009, 'diazepam-induced amnesia', 'is_a', 'amnesia'],
 [9647766, 'ndufs6', 'has homology with', 'bovine translation products'],
 [20510337, 'coenzyme q10', 'suppresses', 'lipid peroxidation'],
 [28851297,
  'aγ(+25 g→a) polymorphism',
  'affects',
  "lyar binding site 5'-ggttat-3'"],
 [16755009, 'elevated plus maze', 'measures', 'memory'],
 [18779591, 'prlr(i146l)', 'is_variant_of', 'prolactin receptor (prlr)'],
 [15858223,
  'valproic acid (vpa)',
  'causes',
  'inflammation of the liver capsule'],
 [1711760,
  '2,3,5-triphenyltetrazolium staining',
  'determines',
  'neuronal injury'],
 [18410508, 'striatal-resident microglia', 'does_not_undergo', 'migration'],
 [27172902, 'cisplatin', 'activates', 'nf-kappab signaling pathway'],
 [21070631,
  'misregulation of inflammation',
  'may contribute to onset of',
  "alzheimer's disease (ad)"],
 [28584052, 'p.arg284pro', 'reduces', 'glycosylation activity'],
 [25263533, 'b-cell maturation', 'contributes_to', 'immune memory'],
 [10788334,
  'brca1 abnormalities',
  'occur in',
  '26 families with both breast and ovarian cancers'],
 [16391785, 'dock8', 'expressed_in', 'lungs'],
 [18593936, 'bladder tumor', 'modeled_by', 'athymic nude mice'],
 [20579626, 'c.1052dela', 'causes', 'frameshift'],
 [24055495,
  'parenteral administration',
  'used_to_generate',
  'animal aging model'],
 [25979836, 'pak2', 'is activated via', 'protein kinase c (pkc)'],
 [11009181,
  'apomorphine rescue injections',
  'benefits',
  'complex on-off motor swings'],
 [15122711, 'g1681a mutation', 'results_in', 'ala467thr substitution'],
 [20846357, 'severe respiratory failure', 'resulted_in', 'death'],
 [17277899,
  'basques',
  'show no substantial genetic heterogeneity with',
  'european populations'],
 [20528871, 'salvage therapy', 'used_for', 'refractory t-cell leukaemia'],
 [17854040, 'c domain', 'located_in', 'hbv rt enzyme'],
 [18439317, '-1607 promoter polymorphism', 'located_in', 'mmp1 gene'],
 [20105310, 'microarray', 'examined', 'inflammation'],
 [15893386, 'propofol infusion', 'used_during', 'general anesthesia'],
 [15686794, 'intravenous amiodarone loading', 'involves', 'amiodarone'],
 [16574713, 'moderate mdma users', 'had fewer than', '55 lifetime tablets'],
 [23952588, 'onset age', 'predicts', 'levodopa-induced dyskinesia'],
 [28584052, 'o-glcnacase', 'opposes', 'ogt'],
 [27941998,
  'mutation in the gene coding for desmin',
  'causes',
  'desminopathies'],
 [19672862, 'pkcalpha', 'activates', 'erk-dependent proliferative pathways'],
 [15957009, 'ro4368554', 'facilitates', 'object memory'],
 [15807692, 'ivs51 + 1g-->a', 'located_in', 'intron 51'],
 [30442153, 'beta-amyloid', 'induces', 'reactive astrocytes'],
 [16781314,
  'skin biopsy',
  'reveals',
  'reduced number of small, poorly formed desmosomes'],
 [19891556, 'cyp2c19 genotype', 'influences', 'clopidogrel pharmacokinetics'],
 [19996135,
  'perioperative seizures',
  'monitored_by',
  'electroencephalographic activity'],
 [27248656, 'hsp90beta knockdown', 'reduces', 'hsp90beta'],
 [17065198, 'sunlight', 'contains_risk_factor', 'uv radiation'],
 [19365571,
  'carbohydrate sulfotransferase gene (chst6)',
  'analyzed by',
  'direct sequencing'],
 [15770495, '217_218insc', 'mutation_in', 'srd5a2'],
 [17065198,
  'non-melanoma skin cancers (nmscs)',
  'predominantly_include',
  'squamous cell carcinomas (sccs)']]

### False Negatives

In [ ]:
if DATASET_SPLIT == "train":
    # ---------- False negatives ----------
    relation_fn = epi_log["errors"]["errors"]["relations"]["false_negatives"]

    print(f"Count: {len(relation_fn)}")

    display(sample_errors(relation_fn, sample_size=200))

Count: 3834
Sample size: 200

[[25263533, 't-cell receptor', 'Negative_Correlation', 'bcl6'],
 [16786513, 'mcardle disease', 'Association', 'c.1471c>t'],
 [18541230,
  'puromycin aminonucleoside',
  'Positive_Correlation',
  'renal dysfunction'],
 [20046642, 'carmustine', 'Positive_Correlation', 'malondialdehyde'],
 [20583543, '46,xy dsd', 'Association', 'srd5a2'],
 [10788334, 'brca1', 'Association', 'brca1 abnormalities'],
 [16596970,
  'pilocarpine',
  'Positive_Correlation',
  'impairment in auditory location discrimination'],
 [19841052, 'crack cocaine', 'Positive_Correlation', 'hiv infection'],
 [17379047, 'valsartan', 'Comparison', 'hydrochlorothiazide'],
 [24971338, 'cyclosporine', 'Association', 'tp53'],
 [16786513, 'mcardle disease', 'Association', 'p.k543x'],
 [27084744, 'sox10', 'Association', 'cancer'],
 [24126708, 'levodopa', 'Negative_Correlation', "parkinson's disease"],
 [19218574, 'phosphatidylinositol 3-kinase', 'Association', 'glucose'],
 [21810259, 'ido', 'Association', 'hiv-1-infected'],
 [17615423, 'amiodarone', 'Positive_Correlation', 'acute renal failure'],
 [20034406, 'ccr2', 'Association', 'neuroinflammation'],
 [19508969,
  'meckel-gruber syndrome (mks) type 3',
  'Positive_Correlation',
  'p.w290l'],
 [18791947, 'bernard-soulier syndrome', 'Negative_Correlation', 'gpibalpha'],
 [18422462, 'hiv-infected', 'Negative_Correlation', 'efavirenz'],
 [20722491, 'capecitabine', 'Positive_Correlation', 'nausea'],
 [27974047, 'etv6', 'Association', 'ntrk3'],
 [20533999, 'l-dihydroxyphenylalanine', 'Association', 'neurotoxicity'],
 [16786513, 'autosomal recessive disorder', 'Association', 'glycogen'],
 [17035713, 'cysteine proteases', 'Positive_Correlation', 'cisplatin'],
 [16586083, 'prostanoid', 'Association', 'cyclooxygenase inhibitors'],
 [24709919, 're, rg1, and rb1 ginsenosides', 'Negative_Correlation', 'opioid'],
 [27084744, 'dapt', 'Association', 'cd133'],
 [24132704, 'low-density lipoprotein receptor', 'Association', 'hyperlipemia'],
 [15033202,
  'nijmegen breakage syndrome',
  'Positive_Correlation',
  '5 nucleotide deletion'],
 [30442153,
  'glial fibrillary acidic protein',
  'Association',
  "alzheimer's disease"],
 [19365571, 'macular corneal dystrophy', 'Association', 'c.892c>t'],
 [25979836, 'neurotransmitters', 'Association', 'src'],
 [24055495, 'glut4', 'Association', 'glucose'],
 [20415560, 'vitamin e', 'Negative_Correlation', 'stroke'],
 [15623763, 'gcd type iii', 'Association', 'tgfbi'],
 [18410508, 'mptp', 'Association', 'neurotoxicity'],
 [21496008, 'dup24bp', 'Positive_Correlation', 'intellectual disability'],
 [18270997, 'val158met', 'Association', 'opiate addiction'],
 [19841052, 'hiv seroconversion', 'Positive_Correlation', 'crack cocaine'],
 [19445921, 'isoproterenol', 'Positive_Correlation', 'lactate dehydrogenase'],
 [2422478, 'serotonin', 'Positive_Correlation', 'hypotensive'],
 [16786513, 'mcardle disease', 'Association', 'c.1970_2177del'],
 [24132704, 'diazinon', 'Positive_Correlation', 'ldl'],
 [28260056, 'pi3k', 'Negative_Correlation', 'ly294002'],
 [19463742, 'glucose', 'Positive_Correlation', 'insulin'],
 [26027517, 'pi3k', 'Association', 'akt'],
 [22859398, 'nos2', 'Association', 'prostate cancer'],
 [28204828, 'tieg1', 'Association', 'bax'],
 [16720068, 'extrapyramidal symptoms', 'Positive_Correlation', 'alprazolam'],
 [25263533, 'cd25', 'Positive_Correlation', 'iga'],
 [16725121, 'cocaine', 'Positive_Correlation', 'convulsions'],
 [21666969, 'cannabinoid receptor', 'Association', 'weight loss'],
 [28411266, 'sulfonylurea receptor', 'Association', 'sulfonylurea'],
 [24971338, 'sirolimus', 'Comparison', 'cyclosporine'],
 [25305591,
  'pituitary adenylyl cyclase-activating polypeptide',
  'Negative_Correlation',
  'inflammatory'],
 [18593936, 'curcumin', 'Negative_Correlation', 'bladder cancer'],
 [19048115, 'ovarian serous carcinomas', 'Association', 'neurofibromin 1'],
 [16391785, "5-aza-2'-deoxy-cytidine", 'Negative_Correlation', 'lung cancer'],
 [27941998, 'desmin', 'Association', 'desminopathy'],
 [27172902, 'cisplatin', 'Negative_Correlation', 'cd86'],
 [28512644, 'hgf', 'Association', 'sod2'],
 [18672102, '125-126insaa', 'Association', 'tetralogy of fallot'],
 [19923525, 'nimodipine', 'Association', 'hypotension'],
 [18182964, 'clonidine', 'Positive_Correlation', 'bradycardia'],
 [15858223, 'valproic acid', 'Association', 'liver toxicity'],
 [28260056, 'reactive oxygen species', 'Association', 'mtor'],
 [18672102, 'congenital heart disease', 'Association', 'e359k'],
 [29045486, 'thiamine', 'Association', 'thiamine deficiency'],
 [17683901, 'g380r', 'Positive_Correlation', 'achondroplasia'],
 [8755918,
  '137-bp insertion',
  'Positive_Correlation',
  'ataxia-telangiectasia'],
 [20528871,
  'etoposide',
  'Negative_Correlation',
  't-cell lymphoblastic leukaemia and lymphoma'],
 [15461822, 'delta30-4995', 'Association', 'dengue'],
 [28368537, 'janus kinase', 'Association', 'lif receptor'],
 [15630069, 'olanzapine', 'Association', 'glucose'],
 [28151486, 'doxycycline', 'Association', 'scid'],
 [18310445,
  'bone morphogenetic proteins (bmp)-4',
  'Negative_Correlation',
  'fsh'],
 [18310445, 'gnrh', 'Positive_Correlation', 'fsh'],
 [19058010, 'isoproterenol', 'Positive_Correlation', 'ca+2 atpase'],
 [28487437, 'streptozotocin', 'Positive_Correlation', 'hyperglycemia'],
 [26516699, 'kras', 'Association', 'mir-150'],
 [16364460, 'ritanserin', 'Negative_Correlation', 'amnesia'],
 [20034406, 'seizures', 'Association', 'ccr2'],
 [26516699, 'kras', 'Association', 'mir-138'],
 [17042910, 'hypertension', 'Negative_Correlation', 'nitric oxide'],
 [16755009,
  'extract of daucus carota seeds',
  'Negative_Correlation',
  'cognitive dysfunctions'],
 [20046642, 'metallothionein', 'Negative_Correlation', 'malondialdehyde'],
 [27974047, 'gastrointestinal stromal tumors', 'Association', 'znf217'],
 [27643404, 'aldehyde dehydrogenases', 'Association', 'prostate cancer'],
 [27941998,
  'voltage-dependent anion channel 1',
  'Association',
  'mitochondrial dysfunction'],
 [19825989,
  '(r)-(alpha)-(-)-methylhistamine dihydrobromide',
  'Negative_Correlation',
  'tumor'],
 [27959382, 'bach1', 'Positive_Correlation', 'pulmonary fibrosis'],
 [15623763, 'arginine 555-to-tryptophan', 'Association', 'gcd type i'],
 [19058010, 'vitamin e', 'Positive_Correlation', 'na+/ k+ atpase'],
 [27941998,
  'voltage-dependent anion channel 1',
  'Association',
  'desminopathy'],
 [19631624, 'ecstasy', 'Positive_Correlation', 'learning and memory deficits'],
 [19881468, 'lung cancer', 'Positive_Correlation', 'ser326cys'],
 [16391785, 'dock8', 'Association', 'lung and other cancers'],
 [27014915, 'tnfa', 'Association', 'tumor'],
 [10788334, 'breast or ovarian cancer', 'Positive_Correlation', 'c61g'],
 [18356633,
  'hematologic/oncologic disorder',
  'Negative_Correlation',
  'amikacin'],
 [18945288, 'hgd', 'Association', 'alkaptonuria'],
 [22859398, 'rs1800896', 'Negative_Correlation', 'prostate cancer'],
 [18165598, 'bupivacaine', 'Positive_Correlation', 'prostaglandin e2'],
 [20533999, 'l-dihydroxyphenylalanine', 'Association', 'dopamine'],
 [15858223,
  'liver toxicity',
  'Positive_Correlation',
  'alpha-glutathione s-transferase'],
 [20806042, 'c.592c-->t', 'Positive_Correlation', 'microcornea'],
 [15957009, 'ro4368554', 'Negative_Correlation', 'memory deficiency'],
 [20367983, 'tumor', 'Negative_Correlation', 'men1'],
 [17286451, 'rb1', 'Association', 'tumors'],
 [27172902, 'il-10', 'Association', 'inflammatory'],
 [20428796, 'tgf-beta1', 'Positive_Correlation', 'tgf-beta'],
 [17042910, 'atorvastatin', 'Positive_Correlation', 'nitric oxide'],
 [20683499, 'crocin', 'Negative_Correlation', 'neurodegenerative diseases'],
 [25979836, 'bombesin', 'Positive_Correlation', 'amylase'],
 [21695597, 'mhc', 'Association', 'systemic lupus erythematosus'],
 [15145918,
  'clonidine',
  'Positive_Correlation',
  'alpha2-adrenergic and i1-imidazoline receptor'],
 [18827003,
  'hypersensitivity',
  'Association',
  'aspartic acid to histidine substitution at amino acid position 401'],
 [20806042,
  'c.592c-->t',
  'Positive_Correlation',
  'cataract-microcornea syndrome'],
 [20428796, 'tgf-beta', 'Positive_Correlation', 'keloid scars'],
 [25622904, 'deptor', 'Association', 'kras'],
 [16725121, 'lidocaine', 'Positive_Correlation', 'convulsions'],
 [18270997,
  'catechol-o-methyltransferase',
  'Negative_Correlation',
  'dopamine'],
 [28472177, 'ubiquitin carboxyl-terminal esterase l1', 'Association', 'aqp4'],
 [16369751,
  '5-fluorouracil',
  'Positive_Correlation',
  'right bundle branch block'],
 [22303482, 'hlx1', 'Association', 'gm-csf'],
 [21666969, 'il-6', 'Association', 'weight loss'],
 [17286451, 'rb1', 'Association', 'retinoblastoma'],
 [15064320, 'testosterone', 'Association', 'human chorionic gonadotropin'],
 [15755837, 'folate', 'Negative_Correlation', 'preterm delivery'],
 [2422478, 'serotonin', 'Association', '5,7-dihydroxytryptamine'],
 [18809400, 'peripheral neuropathy', 'Positive_Correlation', 'cisplatin'],
 [27084744, 'cancer', 'Association', 'rock'],
 [25986755, 'caffeine', 'Negative_Correlation', 'podocin'],
 [21699520, 'cancer', 'Association', 'p.e947stop'],
 [25622904, 'p21', 'Negative_Correlation', 'tumor'],
 [15749661, 'hemochromatosis', 'Association', 'transferrin receptor 2'],
 [28777492,
  'gankyrin',
  'Bind',
  'src homology 2 domain-containing protein tyrosine phosphatase-1'],
 [19108278, 'propranolol', 'Negative_Correlation', 'cardiac arrhythmias'],
 [25979836, 'cck', 'Association', 'src'],
 [17344330, 'buprenorphine', 'Negative_Correlation', 'heroin dependence'],
 [19889778, 'p120t', 'Association', 'hbsag'],
 [27134166, 'tumor', 'Association', 'glutamine'],
 [15614572, 'catalepsy', 'Positive_Correlation', 'apomorphine'],
 [18779591, 'prolactin', 'Association', 'benign breast tumors'],
 [17965424, 'aspirin', 'Negative_Correlation', 'rheumatoid arthritis'],
 [15748645, 'skin cancer', 'Positive_Correlation', 'ornithine decarboxylase'],
 [17194457,
  'testosterone',
  'Negative_Correlation',
  '5-hydroxyindoleacetic acid'],
 [27860244, 'rheumatoid arthritis', 'Association', 'p65'],
 [26516699, 'pancreatic cancer', 'Association', 'trkra'],
 [19037252,
  'diffuse mesangial sclerosis',
  'Association',
  'phospholipase c epsilon 1'],
 [28747658, 'p17', 'Association', 'mapk8'],
 [16584858, 'dimethyl sulphoxide', 'Association', 'superoxide dismutase'],
 [17304550, 'macrocephaly', 'Association', 'synaptotagmin'],
 [19672862, 'cyclin-dependent kinase', 'Negative_Correlation', 'p27'],
 [24768818, 'collagen receptor', 'Negative_Correlation', 'ponatinib'],
 [18541230, 'antithrombin', 'Negative_Correlation', 'nephrotic syndrome'],
 [20558148, 'nmda receptors', 'Negative_Correlation', 'mk-801'],
 [26102294, 'etoposide', 'Positive_Correlation', 'ampk'],
 [15630069, 'schizoaffective disorder', 'Negative_Correlation', 'clozapine'],
 [19692487, 'licl', 'Positive_Correlation', 'pge(2)'],
 [16720068, 'extrapyramidal symptoms', 'Positive_Correlation', 'paroxetine'],
 [18340638, 'azathioprine', 'Positive_Correlation', 'phosphatidylserine'],
 [8755918, 'atm', 'Association', 'cerebellar ataxia'],
 [28512644, 'g7958a', 'Association', 'erysipelas'],
 [11773892, 'end-stage renal disease', 'Positive_Correlation', 'creatinine'],
 [17006606, 'nuclear factor of kappa b', 'Association', 'cancer'],
 [16369751, 'alpha-fluoro-beta-alanine', 'Negative_Correlation', 's-1'],
 [16720068, 'muscle rigidity', 'Negative_Correlation', 'diazepam'],
 [28075473, 'toll-like receptor 4', 'Association', 'interleukin-17'],
 [28747658, 'p17', 'Association', 'casp-7'],
 [19218574,
  'phosphatidylinositol 3-kinase',
  'Association',
  '17-hydroxyprogesterone'],
 [27134166, 'tumor', 'Association', 'p-s6'],
 [15897593, 'doxorubicin', 'Positive_Correlation', 'weight loss'],
 [19692487, 'lithium', 'Positive_Correlation', 'polyuria'],
 [22303482, 'gm-csf', 'Association', 'peptidoglycan'],
 [15523499,
  'cardiovascular and metabolic disorders',
  'Association',
  'beta adrenergic receptor'],
 [7905839, 'cyclic amp', 'Association', 'mu opiate receptor'],
 [16160878, 'urotensin-ii', 'Positive_Correlation', 'prolactin'],
 [20335448, 'arginine 714', 'Association', 'hypoglycemia'],
 [27974047, 'tumors', 'Association', 'tacc1'],
 [19463742, 'insulin', 'Association', 'c-jun n-terminal kinase'],
 [19721134, 'pilocarpine', 'Negative_Correlation', 'ouabain'],
 [28260056, 'hypoxia', 'Association', 'pi3k'],
 [20105280, 'p27kip1', 'Positive_Correlation', 'ras'],
 [15623763,
  'tgfbi',
  'Association',
  'lattice and granular corneal dystrophies'],
 [16720068,
  'bromocriptine',
  'Negative_Correlation',
  'extrapyramidal symptoms'],
 [15649253, 'primary malignant lymphoma of the brain', 'Association', 'p14'],
 [25218136, 'leucine', 'Positive_Correlation', 'raga-d'],
 [28416580, 'tspo', 'Association', 'brain injury'],
 [25622904, 'sag', 'Association', 'nf1'],
 [28468941, 'pulmonary hypertension', 'Association', 'smad'],
 [19058010, 'vitamin e', 'Positive_Correlation', 'antioxidants'],
 [18442015, 'corn oil', 'Positive_Correlation', 'atherosclerotic'],
 [28512644, 'cat', 'Association', 'erysipelas'],
 [17379047,
  'hydrochlorothiazide',
  'Negative_Correlation',
  'essential hypertension'],
 [18083142, 'norepinephrine', 'Association', 'cocaine'],
 [25979836, 'p21 activated kinase 2', 'Positive_Correlation', 'tpa'],
 [19692487, 'licl', 'Positive_Correlation', 'mpges-1'],
 [20105310, 'lipid', 'Association', 'dgat1']]

## Entities

### False Positives

In [ ]:
if DATASET_SPLIT == "train":
    # ---------- False positives ----------
    entities_fp = epi_log["errors"]["errors"]["entities"]["false_positives"]

    print(f"Count: {len(entities_fp)}")

    display(sample_errors(entities_fp))

Count: 10538
Sample size: 20

[[18410548, 'family history', 'clinical_factor'],
 [15266215, 'osteoarthritis', 'disease'],
 [16810074, 'venomotor tone', 'physiological process'],
 [26102294, 'persistent dna damage', 'biological process'],
 [16634859, 'nondrinking group', 'control group'],
 [20129423, 'liver', 'organ'],
 [16391785, 'trichostatin a', 'chemical compound'],
 [15749661, '1469t->g', 'genetic variant'],
 [26731607, 'p38 mitogen-activated protein kinase', 'protein'],
 [25622904, 'cellular senescence', 'biological process'],
 [18487244, 'catalytic domain', 'protein domain'],
 [17615423, 'alanine aminotransferase', 'laboratory_measurement'],
 [28472177, 'cell adhesion', 'biological process'],
 [24911645, 'animals', 'organism'],
 [16843501, 'endogenous oxidative dna lesions', 'DNA damage'],
 [27640183, 'prolonged epo exposure', 'experimental intervention'],
 [23791840, 'wild-type (wt) embryos', 'biological specimen'],
 [15188772, 'medication labeling', 'intervention'],
 [19306381, 'focal adhesion kinase', 'kinase'],
 [9647766, 'human chromosome 1', 'chromosome']]

### False Negatives

In [ ]:
if DATASET_SPLIT == "train":
    # ---------- False negatives ----------
    entities_fn = epi_log["errors"]["errors"]["entities"]["false_negatives"]

    print(f"Count: {len(entities_fn)}")

    display(sample_errors(entities_fn))

Count: 6087
Sample size: 20

[[16120104, '111g', 'SequenceVariant'],
 [8755918, 'cerebellar ataxia', 'DiseaseOrPhenotypicFeature'],
 [20528871, 'cyclophosphamide', 'ChemicalEntity'],
 [21135151, 'aids', 'DiseaseOrPhenotypicFeature'],
 [22104738, 'c.920t>g', 'SequenceVariant'],
 [15278670, 'convulsions', 'DiseaseOrPhenotypicFeature'],
 [15523499, 'beta-adrenergic receptors', 'GeneOrGeneProduct'],
 [24132704, 'corn oil', 'ChemicalEntity'],
 [20105310, 'asp receptor', 'GeneOrGeneProduct'],
 [28260056, 'threonine protein kinase b', 'GeneOrGeneProduct'],
 [17221831, 'purine nucleoside phosphorylase', 'GeneOrGeneProduct'],
 [15630069, 'diabetes', 'DiseaseOrPhenotypicFeature'],
 [15200408, 'up', 'GeneOrGeneProduct'],
 [17035713, 'tumor', 'DiseaseOrPhenotypicFeature'],
 [18674790, 'rats', 'OrganismTaxon'],
 [16369751, 'malignancies', 'DiseaseOrPhenotypicFeature'],
 [27999109, 'insulitis', 'DiseaseOrPhenotypicFeature'],
 [27248656, 'tnf-alpha', 'GeneOrGeneProduct'],
 [24743235, 'csf-1r', 'GeneOrGeneProduct'],
 [15241482, '-107c/t', 'SequenceVariant']]